// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nearconnect/DarkCityscape.tsx": () => import("../components/mockups/nearconnect/DarkCityscape.tsx"),
  "./components/mockups/nearconnect/GlassMorphism.tsx": () => import("../components/mockups/nearconnect/GlassMorphism.tsx"),
  "./components/mockups/nearconnect/WarmCommunity.tsx": () => import("../components/mockups/nearconnect/WarmCommunity.tsx")
};
